# Generic
width = 2100
height = 7400
earliest = "120 mya"
latest = "present"
out = "temps.png"
rotate = true

[stratigraphy]
source = "assets/stratigraphy.toml"

[timescale]
offset = 1000
tacks = [
    "10 bya",

    "6 bya", "4 bya", "2.5 bya", "1.5 bya", "1 bya",
    "600 mya", "400 mya", "250 mya", "150 mya", "100 mya",
    "60 mya", "40 mya", "25 mya", "15 mya", "10 mya",

    "6 mya", "4 mya", "2.5 mya", "1.5 mya", "1 mya",
    "600 kya", "400 kya", "250 kya", "150 kya", "100 kya",
    "60 kya", "40 kya", "25 kya", "15 kya", "10 kya",

    "3500 BC", "1500 BC", "1 AD", "700 AD", "1200 AD", "1500 AD",
    "1700 AD", "1820 AD", "1900 AD", "1940 AD", "1970 AD", "1990 AD",
    "2005 AD", "2015 AD", "2020 AD", "2022-02 AD", "2023-06 AD"
]

[temps]
offset = 1400
magnifier = 30
