"13.787 bya" = "Big Bang"
# "13.6 bya" = "First confimed star, SMSS J0313−6708"
"4.6 bya" = "Formation and evolution of the Solar System"
# "4.54 bya" = "Earth is formed"
# "4.5 bya" = "Theia impacts Earth, forming the Moon"
"4.1 bya" = "Earliest known life forms"
# "2.5 bya" = "Huronian glaciation"
"2.460 bya" = "Great Oxidation Event"
"2.2 bya" = "Huronian glaciation ends"

# https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1689654/
"1.576 bya" = "Plants, animals, and fungi diverge"

"1.26 bya" = "Rodinia starts to form"
"760 mya" = "First Animalia"
# "717 mya" = "Sturtian glaciation begins"
"650 mya" = "Pannotia forms"
# "560 mya" = "Pannotia breaks up"
"538.8 mya" = "Cambrian explosion"
# "440 mya" = "Andean-Saharan glaciation" # 460-420
"445 mya" = "Late Ordovician mass extinction caused by Andean-Saharan glaciation"
"372 mya" = "Late Devonian extinction"
# "360 mya" = "Late Paleozoic icehouse begins"
"335 mya" = "Pangaea forms"
"312 mya" = "Basal amniotes (ancestors of reptiles and mammals)"
# "259 mya" = "Capitanian mass extinction event"
# "255 mya" = "Late Paleozoic icehouse ends"
"251.9 mya" = "Permian–Triassic extinction event, aka the \"Great Dying\""
"201.4 mya" = "Triassic–Jurassic extinction event"
# "200 mya" = "Pangaea begins to break up"
# "66.25 mya" = "Deccan Traps"
"66.043 mya" = "Cretaceous–Paleogene extinction event, non-avian dinosaurs are extinct"
"25 mya" = "Apes diverge from the Old World monkeys"
"18 mya" = "Great apes diverge from gibbons"
"14 mya" = "Hominins diverge from orangutans"
"7 mya" = "Hominini diverge from gorillas"
"5 mya" = "Humans diverge from chimpanzees" # actually 3-5
"4.2 mya" = "Earliest Australopithecus"
"3.4 mya" = "Earliest stone tools"
"2.75 mya" = "LD 350-1, earliest known specimen of genus Homo"
"2.12 mya" = "Out of Africa I - human presence in China"
"1.8 mya" = "Oldest known human skeletal remains outside of Africa (Homo erectus)"
"430 kya" = "Earliest neanderthals (rough date)"
"250 kya" = "Out of Africa II - Homo sapiens" # 300-200 kya
"108 kya" = "The last known population of Homo erectus on Java goes extinct"
"65 kya" = "Human migration to Australia"
"40 kya" = "Neanderthal extinction"
"26.5 kya" = "Last Glacial Maximum begins"
"20 kya" = "Last Glacial Maximum ends"
"17 kya" = "Human migration to the Americas" # though estimates range from 15k to (newer estimate) 25k
"14.6 kya" = "African humid period begins"
"12.9 kya" = "Younger Dryas begins"
"11.7 kya" = "Younger Dryas ends"
"10.5 kya" = "Cattle domesticated"
"8.2 kya" = "8.2-kiloyear event (sudden cooling)"
# "5.5 kya" = "African humid period ends"
"3500 BC" = "First cuneiform; african humid period ends; horse domesticated"
# "3250 BC" = "First hieroglyphics"
"2600 BC" = "Great Pyramid of Giza"
"4.2 kya" = "4.2-kiloyear event (sudden aridification)"
"1750 BC" = "Code of Hammurabi"
"1200 BC" = "Late Bronze Age collapse"
"550 BC" = "Achaemenid Empire under Cyrus the Great"
"323 BC" = "Alexander the Great dies in Babylon"
"44 BC" = "Julius Caesar assassinated"
"319 AD" = "Gupta Empire established"
"476 AD" = "Fall of the Western Roman Empire"
# "555 AD" = "Byzantine Empire under Justinian the Great, at its greatest extent"
"622 AD" = "The Hijrah (Muhammad's migration from Mecca to Medina)"
"800 AD" = "Charlemagne crowned as Roman Emperor"
"1066 AD" = "Norman conquest of England"
# "1204 AD" = "Sack of Constantinople"
"1259 AD" = "Mongol Empire before fracture"
"1347 AD" = "The Black Death in Europe"
"1492 AD" = "Spain's discovery of the New World"
# "1517 AD" = "Protestant Reformation - Martin Luther publishes the Ninety-five Theses"
"1566 AD" = "Suleiman the Great dies"
"1648 AD" = "Thirty Years' War ends"
"1763 AD" = "Seven Years' War ends"
"1812 AD" = "Napoleonic France at peak territorial control"
"1871 AD" = "Unification of Germany after the Franco-Prussian war"
"1914 AD" = "World War I begins"
# "1918 AD" = "World War I ends"
"1939 AD" = "World War II begins"
"1945 AD" = "World War II ends"
"1962 AD" = "Cuban Missile Crisis"
"1991 AD" = "Dissolution of the Soviet Union"
"2001 AD" = "September 11 attacks"
"2015 AD" = "ISIS at peak territorial control"
"2020 AD" = "COVID-19 pandemic"
"2022 AD" = "Russia invades Ukraine"
