
[eon."Before life"]
color = "#AE027E"
start = "4423 mya"

[eon."Unicellular life"]
color = "#F0047F"
start = "3423 mya"

[eon."Multicellular life"]
color = "#FEB342"
start = "1423 mya"

[eon."Ancient ocean with predators"]
color = "#99C08D"
start = "423 mya"

[eon."Invasion of land"]
color = "#B3E1B6"
start = "323 mya"

[eon."Terrestrial diversity"]
color = "#CB8C37"
start = "253 mya"

[eon."Lower CO2, steppes"]
color = "#67A599"
start = "210 mya"

[eon."Deserts and rainforests"]
color = "#F04028"
start = "160 mya"

[eon."Allopatry and ice age"]
color = "#34B2C9"
start = "123 mya"

[eon."Island activity"]
color = "#7FC64E"
start = "93 mya"

[eon."Post-mass extinction"]
color = "#FD9A52"
start = "33 mya"

[eon."Sapience"]
color = "#F9F97F"
start = "4 mya"

[eon."History"]
color = "#FDEDEC"
start = "0.5 mya"
