# Source: https://stratigraphy.org/chart
# Version: https://stratigraphy.org/ICSchart/ChronostratChart2023-09.pdf

[eon."Ранняя Вселенная"] # Not a real eon; I wanted to fill in the gap
color = "#131313"
start = "13.787 млрд лет"
text_color = "#eeeeee"

[eon.Hadean]
color = "#AE027E"
start = "4567 млн лет"

[eon."Архей"]
color = "#F0047F"
child = "Eoarchean"

[era.Eoarchean]
color = "#DA037F"
start = "4031 млн лет"

[era.Paleoarchean]
color = "#F4449F"
start = "3600 млн лет"

[era.Mesoarchean]
color = "#F768A9"
start = "3200 млн лет"

[era.Neoarchean]
color = "#F99BC1"
start = "2800 млн лет"

[eon."Протерозой"]
color = "#F73563"
child = "Палеопротерозой"

[era."Палеопротерозой"]
color = "#F74370"
child = "Siderian"

[period.Siderian]
color = "#F74F7C"
start = "2500 млн лет"

[period.Rhyacian]
color = "#F75B89"
start = "2300 млн лет"

[period.Orosirian]
color = "#F76898"
start = "2050 млн лет"

[period.Statherian]
color = "#F875A7"
start = "1800 млн лет"

[era."Мезопротерозой"]
color = "#FDB462"
child = "Calymmian"

[period.Calymmian]
color = "#FDC07A"
start = "1600 млн лет"

[period.Ectasian]
color = "#FDCC8A"
start = "1400 млн лет"

[period.Stenian]
color = "#FED99A"
start = "1200 млн лет"

[era."Неопротерозой"]
color = "#FEB342"
child = "Тоний"

[period."Тоний"]
color = "#FEBF4E"
start = "1000 млн лет"

[period.Cryogenian]
color = "#FECC5C"
start = "720 млн лет"

[period.Ediacaran]
color = "#FED96A"
start = "635 млн лет"

[eon."Фанерозой"]
color = "#9AD9DD"
child = "Палеозой"

[era."Палеозой"]
color = "#99C08D"
child = "Cambrian"



[period.Cambrian]
color = "#7FA056"
child = "Terreneuvian"

[epoch.Terreneuvian]
color = "#8CB06C"
child = "Fortunian"

[age.Fortunian]
color = "#99B575"
start = "538.8 млн лет"

[age."Stage 2"]
color = "#A6BA80"
start = "529 млн лет"

[epoch."Series 2"]
color = "#99C078"
child = "Stage 3"

[age."Stage 3"]
color = "#A6C583"
start = "521 млн лет"

[age."Stage 4"]
color = "#B3CA8E"
start = "514 млн лет"

[epoch.Miaolingian]
color = "#A6CF86"
child = "Wuliuan"

[age.Wuliuan]
color = "#B3D492"
start = "509 млн лет"

[age.Drumian]
color = "#BFD99D"
start = "504.5 млн лет"

[age.Guzhangian]
color = "#CCDFAA"
start = "500.5 млн лет"

[epoch.Furongian]
color = "#B3E095"
child = "Paibian"

[age.Paibian]
color = "#CCEBAE"
start = "497 млн лет"

[age.Jiangshanian]
color = "#D9F0BB"
start = "494 млн лет"

[age."Stage 10"]
color = "#E6F5C9"
start = "489.5 млн лет"



[period.Ordovician]
color = "#009270"
child = "Lower Ordovician"

[epoch."Lower Ordovician"]
color = "#1A9D6F"
child = "Tremadocian"

[age.Tremadocian]
color = "#33A97E"
start = "485.4 млн лет"

[age.Floian]
color = "#41B087"
start = "477.7 млн лет"

[epoch."Middle Ordovician"]
color = "#4DB47E"
child = "Dapingian"

[age.Dapingian]
color = "#66C092"
start = "470.0 млн лет"

[age.Darriwilian]
color = "#74C69C"
start = "467.3 млн лет"

[epoch."Upper Ordovician"]
color = "#7FCA93"
child = "Sandbian"

[age.Sandbian]
color = "#8CD094"
start = "458.4 млн лет"

[age.Katian]
color = "#99D69F"
start = "453.0 млн лет"

[age.Hirnantian]
color = "#A6DBAB"
start = "445.2 млн лет"



[period.Silurian]
color = "#B3E1B6"
child = "Llandovery"

[epoch.Llandovery]
color = "#99D7B3"
child = "Rhuddanian"

[age.Rhuddanian]
color = "#A6DCB5"
start = "443.8 млн лет"

[age.Aeronian]
color = "#B3E1C2"
start = "440.8 млн лет"

[age.Telychian]
color = "#BFE6CF"
start = "438.5 млн лет"

[epoch.Wenlock]
color = "#B3E1C2"
child = "Sheinwoodian"

[age.Sheinwoodian]
color = "#BFE6C3"
start = "433.4 млн лет"

[age.Homerian]
color = "#CCEBD1"
start = "430.5 млн лет"

[epoch.Ludlow]
color = "#BFE6CF"
child = "Gorstian"

[age.Gorstian]
color = "#CCECDD"
start = "427.4 млн лет"

[age.Ludfordian]
color = "#D9F0DF"
start = "425.6 млн лет"

[epoch.Pridoli]
color = "#E6F5E1"
start = "423.0 млн лет"



[period.Devonian]
color = "#CB8C37"
child = "Lower Devonian"

[epoch."Lower Devonian"]
color = "#E5AC4D"
child = "Lochkovian"

[age.Lochkovian]
color = "#E5B75A"
start = "419.2 млн лет"

[age.Pragian]
color = "#E5C468"
start = "410.8 млн лет"

[age.Emsian]
color = "#E5D075"
start = "407.6 млн лет"

[epoch."Middle Devonian"]
color = "#F1C868"
child = "Eifelian"

[age.Eifelian]
color = "#F1D576"
start = "393.3 млн лет"

[age.Givetian]
color = "#F1E185"
start = "387.7 млн лет"

[epoch."Upper Devonian"]
color = "#F1E19D"
child = "Frasnian"

[age.Frasnian]
color = "#F2EDAD"
start = "382.7 млн лет"

[age.Famennian]
color = "#F2EDB3"
start = "372.2 млн лет"



[period.Carboniferous]
color = "#67A599"
child = "Lower Mississippian"

# Mississippian - #678F66

[epoch."Lower Mississippian"]
color = "#80AB6C"
child = "Tournaisian"

[age.Tournaisian]
color = "#8CB06C"
start = "358.9 млн лет"

[epoch."Middle Mississippian"]
color = "#99B46C"
child = "Visean"

[age.Visean]
color = "#A6B96C"
start = "346.7 млн лет"

[epoch."Upper Mississippian"]
color = "#B3BE6C"
child = "Serpukhovian"

[age.Serpukhovian]
color = "#BFC26B"
start = "330.9 млн лет"

# Pennsylvanian - #7EBCC6

[epoch."Lower Pennsylvanian"]
color = "#8CBEB4"
child = "Bashkirian"

[age.Bashkirian]
color = "#99C2B5"
start = "323.2 млн лет"

[epoch."Middle Pennsylvanian"]
color = "#A6C7B7"
child = "Moscovian"

[age.Moscovian]
color = "#B3CBB9"
start = "315.2 млн лет"

[epoch."Upper Pennsylvanian"]
color = "#BFD0BA"
child = "Kasimovian"

[age.Kasimovian]
color = "#BFD0C5"
start = "307.0 млн лет"

[age.Gzhelian]
color = "#CCD4C7"
start = "303.7 млн лет"



[period.Permian]
color = "#F04028"
child = "Cisuralian"

[epoch.Cisuralian]
color = "#EF5845"
child = "Asselian"

[age.Asselian]
color = "#E36350"
start = "298.9 млн лет"

[age.Sakmarian]
color = "#E36F5C"
start = "293.52 млн лет"

[age.Artinskian]
color = "#E37B68"
start = "290.1 млн лет"

[age.Kungurian]
color = "#E38776"
start = "283.5 млн лет"

[epoch.Guadalupian]
color = "#FB745C"
child = "Roadian"

[age.Roadian]
color = "#FB8069"
start = "273.01 млн лет"

[age.Wordian]
color = "#FB8D76"
start = "266.9 млн лет"

[age.Capitanian]
color = "#FB9A85"
start = "264.28 млн лет"

[epoch.Lopingian]
color = "#FBA794"
child = "Wuchiapingian"

[age.Wuchiapingian]
color = "#FCB4A2"
start = "259.51 млн лет"

[age.Changhsingian]
color = "#FCC0B2"
start = "254.14 млн лет"



[era."Мезозой"]
color = "#67C5CA"
child = "Триас"

[period."Триас"]
color = "#812B92"
child = "Lower Triassic"

[epoch."Lower Triassic"]
color = "#983999"
child = "Induan"

[age.Induan]
color = "#A4469F"
start = "251.902 млн лет"

[age.Olenekian]
color = "#B051A5"
start = "251.2 млн лет"

[epoch."Middle Triassic"]
color = "#B168B1"
child = "Anisian"

[age.Anisian]
color = "#BC75B7"
start = "247.2 млн лет"

[age.Ladinian]
color = "#C983BF"
start = "242 млн лет"

[epoch."Upper Triassic"]
color = "#BD8CC3"
child = "Carnian"

[age.Carnian]
color = "#C99BCB"
start = "237 млн лет"

[age.Norian]
color = "#D6AAD3"
start = "227 млн лет"

[age.Rhaetian]
color = "#E3B9DB"
start = "208.5 млн лет"




[period."Юра"]
color = "#34B2C9"
child = "Lower Jurassic"

[epoch."Lower Jurassic"]
color = "#42AED0"
child = "Hettangian"

[age.Hettangian]
color = "#4EB3D3"
start = "201.4 млн лет"

[age.Sinemurian]
color = "#67BCD8"
start = "199.5 млн лет"

[age.Pliensbachian]
color = "#80C5DD"
start = "192.9 млн лет"

[age.Toarcian]
color = "#99CEE3"
start = "184.2 млн лет"

[epoch."Middle Jurassic"]
color = "#80CFD8"
child = "Aalenian"

[age.Aalenian]
color = "#9AD9DD"
start = "174.7 млн лет"

[age.Bajocian]
color = "#A6DDE0"
start = "170.9 млн лет"

[age.Bathonian]
color = "#B3E2E3"
start = "168.2 млн лет"

[age.Callovian]
color = "#BFE7E5"
start = "165.3 млн лет"

[epoch."Upper Jurassic"]
color = "#B3E3EE"
child = "Oxfordian"

[age.Oxfordian]
color = "#BFE7F1"
start = "161.5 млн лет"

[age.Kimmeridgian]
color = "#CCECF4"
start = "154.8 млн лет"

[age.Tithonian]
color = "#D9F1F7"
start = "149.2 млн лет"



[period."Мел"]
color = "#7FC64E"
child = "Нижний Мел"

[epoch."Нижний Мел"]
color = "#8CCD57"
child = "Berriasian"

[age.Berriasian]
color = "#8CCD60"
start = "145.0 млн лет"

[age.Valanginian]
color = "#99D36A"
start = "139.8 млн лет"

[age.Hauterivian]
color = "#A6D975"
start = "132.6 млн лет"

[age.Barremian]
color = "#B3DF7F"
start = "125.77 млн лет"

[age.Aptian]
color = "#BFE48A"
start = "121.4 млн лет"

[age.Albian]
color = "#CCEA97"
start = "113.0 млн лет"

[epoch."Верхний Мел"]
color = "#A6D84A"
child = "Cenomanian"

[age.Cenomanian]
color = "#B3DE53"
start = "100.5 млн лет"

[age.Turonian]
color = "#BFE35D"
start = "93.9 млн лет"

[age.Coniacian]
color = "#CCE968"
start = "89.8 млн лет"

[age.Santonian]
color = "#D9EF74"
start = "86.3 млн лет"

[age.Campanian]
color = "#E6F47F"
start = "83.6 млн лет"

[age.Maastrichtian]
color = "#F2FA8C"
start = "72.1 млн лет"



[era."Кайнозой"]
color = "#F2F91D"
child = "Палеоген"

[period."Палеоген"]
color = "#FD9A52"
child = "Paleocene"

[epoch.Paleocene]
color = "#FDA75F"
child = "Danian"

[age.Danian]
color = "#FDB462"
start = "66.0 млн лет"

[age.Selandian]
color = "#FEBF65"
start = "61.6 млн лет"

[age.Thanetian]
color = "#FDBF6F"
start = "59.2 млн лет"

[epoch."Эоцен"]
color = "#FDB46C"
child = "Ypresian"

[age.Ypresian]
color = "#FCA773"
start = "56.0 млн лет"

[age.Lutetian]
color = "#FDB482"
start = "47.8 млн лет"

[age.Bartonian]
color = "#FDC091"
start = "41.2 млн лет"

[age.Priabonian]
color = "#FDCDA1"
start = "37.71 млн лет"

[epoch."Олигоцен"]
color = "#FEC07A"
child = "Rupelian"

[age.Rupelian]
color = "#FED99A"
start = "33.9 млн лет"

[age.Chattian]
color = "#FEE6AA"
start = "27.82 млн лет"



[period."Неоген"]
color = "#FFE619"
child = "Миоцен"

[epoch."Миоцен"]
color = "#FFFF00"
child = "Aquitanian"

# Lower/Early Miocene Subseries - #FFEC55

[age.Aquitanian]
color = "#FFFF33"
start = "23.03 млн лет"

[age."Бурдигальский"]
color = "#FFFF41"
start = "20.44 млн лет"

# Middle Miocene Subseries - #FFEC73

[age.Langhian]
color = "#FFFF4D"
start = "15.98 млн лет"

[age.Serravallian]
color = "#FFFF59"
start = "13.82 млн лет"

# Upper/Late Miocene Subseries - #FFEC8C

[age."Тортонский"]
color = "#FFFF66"
start = "11.63 млн лет"

[age."Мессинский"]
color = "#FFFF73"
start = "7.246 млн лет"

[epoch."Плиоцен"]
color = "#FFFF99"
child = "Занклский"

# Lower/Early Pliocene Subseries - #FFF2C3

[age."Занклский"]
color = "#FFFFB3"
start = "5.333 млн лет"

# Upper/Late Pliocene Subseries - #FFF2CD

[age."Пьяченцский"]
color = "#FFFFBF"
start = "3.600 млн лет"



[period."Четвертичный"]
color = "#F9F97F"
child = "Плейстоцен"

[epoch."Плейстоцен"]
color = "#FFEFAF"
child = "Гелазский"

# Lower/Early Pleistocene Subseries - #FFF0B9

[age."Гелазский"]
color = "#FFEDB3"
start = "2.58 млн лет"

[age."Калабрийский"]
color = "#FFF2BA"
start = "1.80 млн лет"

# Middle Pleistocene Subseries - #FFF2C7

[age."Тибанийский"]
color = "#FFF2C7"
start = "0.774 млн лет"

# Upper/Late Pleistocene Subseries - #FFF2D3

[age."Верхний плейстоцен"]
color = "#FFF2D3"
start = "0.129 млн лет"

[epoch."Голоцен"]
color = "#FEEBD2"
child = "Гренландский"

[age."Гренландский"]
color = "#FEECDB"
start = "0.0117 млн лет"

[age."Северогриппианский"]
color = "#FDECE4"
start = "0.0082 млн лет"

[age."Мегхалайский"]
color = "#FDEDEC"
start = "0.0042 млн лет"
